<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright 2009, Olivier Diserens
 */
?>
<div id="generalconfigpanel">
<p class="contentheadicon"><img src="<?php echo $this->images_path?>/config_icon.png" alt="" />&nbsp;</p>
 <p class="contentheadtitle"><?php echo $this->t->_($this->selectedSubMenuLabel)?> : <?php echo $this->t->_($this->selectedConfigMenuLabel." Title")?></p>


 <ul id="generalconfigmenu">
   <?php foreach ($this->config_menu as $menu) {?>
  <li id="confmenu_<?php echo $menu->id?>" <?php if ($menu->class) { ?>class="<?php echo $menu->class?>"<?php }?> onclick="javascript:goTo('<?php echo $menu->getHref()?>');"><a href="<?php echo $menu->getHref()?>"><?php echo $menu->label;?></a></li>
   <?php }?>
 </ul>

 <div id="generalconfigcontent">
 <div id="interfaceconfigpanel" class="configpanel">
 
    <div id="localeformcontent">
     <?php echo $this->partial('forms/localeForm.phtml', array('form' => $this->form, 't' => $this->t, 'message' => $this->message,'images_path' => $this->images_path)); ?>
    </div>
    <div id="configpanelinfos">
      <?php echo $this->t->_('current local time is')." : <strong>".$this->currentlocaltime;?></strong> (<a href="<?php echo $this->url(array('action'=>'dateandtime', 'controller'=>'baseconfiguration'));?>"><?php echo $this->t->_('set up...');?></a>)
    </div>
 </div>
 
 </div>
</div>