<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright 2009, Olivier Diserens
 */
?>
<div id="generalconfigpanel">
<p class="contentheadicon"><img src="<?php echo $this->images_path?>/config_icon.png" alt="" />&nbsp;</p>
 <p class="contentheadtitle"><?php echo $this->t->_($this->selectedSubMenuLabel)?> : <?php echo $this->t->_($this->selectedConfigMenuLabel." Title")?></p>
 
 <?php echo $this->partial('layouts/configmenu.phtml', array('config_menu' => $this->config_menu)); ?>
 
 <div id="generalconfigcontent">
 <div id="interfaceconfigpanel" class="configpanel">
 <form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>" id="<?php echo $this->form->getId()?>">
 
  <h1><span class="texth1">
        <?php echo $this->InputRow($this->form->getElement('selectinterface'),array('nobox'=>true));?> 
      </span><span id="reloadallnetwork">
    <?php if (! Zend_Registry::get('restrictions')->isRestricted('NetworkInterface', 'relaodnetnow')) {?>
    <a href="<?php echo $this->url(array('action' => 'reloadnetwork', 'controller' => 'baseconfiguration'));?>"><?php echo $this->t->_('reload network')?></a>
    <?php }?>
    </span></h1>
    <div id="interfaceformcontent">
     <?php echo $this->partial('forms/networkinterfaceForm.phtml', array('form' => $this->form,'t' => $this->t, 'message' => $this->message, 'images_path' => $this->images_path)); ?>
    </div>
 </form>
 </div>
 </div>
</div>