<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<div id="generalconfigpanel">
    <p class="contentheadicon"><img src="<?php echo $this->images_path ?>/config_icon.png" alt="" />&nbsp;</p>
    <p class="contentheadtitle"><?php echo $this->t->_($this->selectedSubMenuLabel) ?> : <?php echo $this->t->_($this->selectedConfigMenuLabel . " Title") ?></p>


    <ul id="generalconfigmenu">
        <?php foreach ($this->config_menu as $menu) { ?>
            <li id="confmenu_<?php echo $menu->id ?>" <?php if ($menu->class) { ?>class="<?php echo $menu->class ?>" <?php } ?> onclick="javascript:goTo('<?php echo $menu->getHref() ?>');"><a href="<?php echo $menu->getHref() ?>"><?php echo $menu->label; ?></a></li>
        <?php } ?>
    </ul>

    <div id="generalconfigcontent">
        <div id="registrationonfigpanel" class="configpanel">


            <div id="registrationformcontent">
                <?php echo $this->partial('forms/changeHostIdForm.phtml', ['form' => $this->formhostid, 't' => $this->t, 'message' => $this->message, 'images_path' => $this->images_path]); ?>
            </div>

            <hr />
            <?php if (!$this->is_registered) { ?>
                <div id="freetrial">
                    <?php echo $this->partial('forms/freeTrialForm.phtml'); ?>
                </div>
                <hr />
            <?php } ?>
            <div id="commercialoptions">
                <?php echo $this->partial('forms/commercialOptionsForm.phtml', ['is_registered' => $this->is_registered]); ?>
            </div>
            <hr />

            <div id="registrationformcontent">
                <?php echo $this->partial('forms/registrationForm.phtml', ['form' => $this->form, 't' => $this->t, 'message' => $this->message, 'images_path' => $this->images_path]); ?>
            </div>

            <div class="registerstatus">
                <?php echo $this->t->_('System is') ?>
                <?php if ($this->registered == 1) { ?>
                    <span class="okregister"><?php echo $this->t->_('registered'); ?></span>
                <?php } else { ?>
                    <span class="nokregister"><?php echo $this->t->_('unregistered'); ?></span>
                <?php } ?>
            </div>

            <hr />

            <div id="registrationformcontent">
                <?php echo $this->partial('forms/registrationCEForm.phtml', ['form' => $this->formCE, 't' => $this->t, 'message' => $this->message, 'images_path' => $this->images_path]); ?>
            </div>

            <div class="registerstatus">
                <?php echo $this->t->_('System is') ?>
                <?php if ($this->registered == 2) { ?>
                    <span class="okregister"><?php echo $this->t->_('registered'); ?></span>
                <?php } else { ?>
                    <span class="nokregister"><?php echo $this->t->_('unregistered'); ?></span>
                <?php } ?>
            </div>

            <?php if ($this->registered == 2 || $this->registered == 1) { ?>
                <hr />
                <div id="registrationformcontent">
                    <?php echo $this->partial('forms/unregistrationForm.phtml', ['form' => $this->formun, 't' => $this->t, 'message' => $this->message, 'images_path' => $this->images_path, 'registered' => $this->registered]); ?>
                </div>
            <?php } ?>
        </div>


    </div>
</div>
