<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright 2009, Olivier Diserens
 */
?>
<?php echo $this->partial('ajax/monitorstatus/restartservice.phtml', array(
                         'status' => $this->status,
                         'process' => $this->process,
                         'slaveid' => $this->slaveid,
                         't' => $this->t,
                         'images_path' => $this->images_path
)); ?>
