<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright 2009, Olivier Diserens
 */
?>
<div id="tooltip">
</div>
<div id="generalconfigpanel">
<p class="contentheadicon"><img src="<?php echo $this->images_path?>/config_icon.png" alt="" />&nbsp;</p>
 <p class="contentheadtitle"><?php echo $this->t->_($this->selectedSubMenuLabel)?> : <?php echo $this->t->_($this->selectedConfigMenuLabel." Title")?></p>


 <ul id="generalconfigmenu">
   <?php foreach ($this->config_menu as $menu) {?>
  <li id="confmenu_<?php echo $menu->id?>" <?php if ($menu->class) { ?>class="<?php echo $menu->class?>"<?php }?> onclick="javascript:goTo('<?php echo $menu->getHref()?>');"><a href="<?php echo $menu->getHref()?>"><?php echo $menu->label;?></a></li>
   <?php }?>
 </ul>

 <div id="generalconfigcontent">
   <form method="<?php echo $this->listform->getMethod() ?>" action="<?php echo $this->listform->getAction()?>" id="<?php echo $this->listform->getId()?>">
   <?php echo $this->partial('layouts/message.phtml', array('message' => $this->message, 't' => $this->t)); ?>
    <ul class="configlist">
      <?php foreach ($this->filenames as $f) {?>
       <li class="listelement<?php if ($f->getStatus() < 1) {?> listelementdisabled<?php }?>"><?php echo $this->InputRow($this->listform->getElement('list_select_'.$f->getId()),array('field_only'=>true,'nobox'=>true,'post_field_text'=>$f->getParam('rule')));?>
         <?php if ($f->getStatus() < 1) { echo "(".$this->t->_('disabled').")"; } ?>
         <?php if ($f->getComment()) {?>
         <p class="entrycomment">
           <?php if ($f->getStatus() <  1) {?><img src="<?php echo $this->images_path?>/attention_off.png" alt="" />
           <?php } else { ?><img class="listhoverable" src="<?php echo $this->images_path?>/attention.png" alt="" />
           <?php }?>
           <?php echo $f->getComment(); ?></p>
            <p class="hidden"><?php echo $f->getComment()?></p>
         <?php }?>
       </li>
      <?php }?>
    </ul>
  <div class="sublistelement addlistelement">
     <h1>Add a filename expression to block</h1>

     <table>
       
       <tr>
         <td><?php echo $this->t->_('Filename expression')?> : </td>
         <?php echo $this->InputRow($this->listform->getElement('addelement'),array('field_only'=>true,'label_addclass'=>'fieldpanel')); ?>
       </tr>
       <tr>
         <td><?php echo $this->t->_('Comment')?> : </td>
         <td class="fieldpanel"><img src="<?php echo $this->images_path?>/attention.png" class="vertimg" alt="" /><?php echo $this->InputRow($this->listform->getElement('addcomment'),array('field_only'=>true,'nobox'=>true)); ?></td>
       </tr>
     </table>
     <p class="submitlist"><?php echo $this->SubmitRow($this->listform->getElement('add'),array('field_only'=>true,'nobox'=>true));?></p>  
  </div> 
    <div class="sublistelement editremelement">
     <h1>Disable, enable or removed blocked filename</h1>
       <p class="submitlist"><?php echo $this->SubmitRow($this->listform->getElement('disable'),array('field_only'=>true,'nobox'=>true));?></p>
       <p class="submitlist"><?php echo $this->SubmitRow($this->listform->getElement('remove'),array('field_only'=>true,'nobox'=>true));?></p>
   </div>
   </form>
 
 
 </div>
</div>