<!-- HEADER -->
<div id="pagehead">
 <div id="mainheader">
  <img id="mclogo" src="<?php echo $this->baseUrl('images/logo_name.png') ?>" alt="MailCleaner, antispam and antivirus" />
  <img id="mcheadpicture" src="<?php echo $this->baseUrl('images/banner_letters.png') ?>" alt="http://www.mailcleaner.net" />
 </div>
 
</div>

<div id="unloggedmessagebox">
 <div id="popupheader">
  <img src="<?php echo $this->baseUrl('images/release.png'); ?>" alt="" /> <p><?php echo $this->translate('Newsletter has been allowed and released.'); ?></p>
 </div>
<div id="text">
  <p><?php echo $this->translate('The newsletter has been allowed and released. It should be delivered in your mailbox in a few minutes.'); ?></p>
 </div>
</div>