<p class="welcome"><?php echo $this->t->_('Welcome to MailCleaner administration panel')?></p>

<?php 
     $user = Zend_Registry::get('user'); 
     $sysconf = MailCleaner_Config::getInstance();
?>

<?php if ($user && $user->getUserType() == 'administrator') {?>
<div class="globalbloc" style="min-height: 0px; padding-bottom: 12px;">
     <h1>InfoBox by MailCleaner Team</h1>
     <div class="maclasseamoi" style="min-height: 20px; max-height: 240px; padding: 6px 12px; overflow-y: scroll; text-align: justify">
<?php } ?>

<?php
$urltoget='https://www.mailcleaner.net/infobox/';

if ($user && $user->getUserType() == 'administrator') {
        if ($sysconf->getOption('REGISTERED') == "1")
                $urltoget = $urltoget.'mc-info-box.php';
        else
                $urltoget = $urltoget.'mc-ce-info-box.php';
        $curl = curl_init();
	
	curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 3); 
	curl_setopt($curl, CURLOPT_TIMEOUT, 3); //timeout in seconds
        curl_setopt_array($curl, array(
                CURLOPT_RETURNTRANSFER => 1,
                CURLOPT_URL => $urltoget,
                CURLOPT_FAILONERROR => true
        ));
        $result = curl_exec($curl);
        if ($result === false)
          echo "No text or no access to remote server.";
        else
          echo $result;

        echo "</div></div>";
}
?>

<?php if (!$this->is_slave) { ?>
<div id="globalstatsbloc" class="globalbloc globalstatbloc">
  <div id="countsbloc1" class="countsbloc">
  <h1><?php echo $this->t->_('Today\'s counts');?></h1>
  <div id="globalstatsloaading" class="globaldataloading">
    <img src="<?php echo $this->images_path?>/loadingwhitebg.gif" alt="loading" />
  </div>
  </div>
  <div id="countsbloc2" class="countsbloc hidden"></div>
</div>

  <?php $user = Zend_Registry::get('user'); ?>
  <?php if ($user && $user->getUserType() == 'administrator') {?>

<div id="globalstatusbloc" class="globalbloc globalstatusbloc">
   <h1><?php echo $this->t->_('Overall system\'s status')?></h1>
   <div id="globalstatusloaading" class="globaldataloading">
     <img src="<?php echo $this->images_path?>/loadingwhitebg.gif" alt="loading" />
   </div>
</div>

  <?php } ?>

<?php }?>
