<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright 2009, Olivier Diserens
 */
?>
<?php require_once('helpers/DataManager.php');
$baseconf = DataManager::getFileConfig(SystemConfig::$CONFIGFILE_); ?>
<?php echo $this->InputRow($this->form->getElement('listeduristobespam'));?>

<tr>
    <td class="flabel flabeltextarea flabelchecklist"><?php echo $this->t->_('Using these RBLs')?> : </td>
    <td class="fvalue fvaluechecklist">
    <?php foreach ($this->form->_rbl_checks as $check) {
        if (preg_match('/^INACTIVE/',$check->getLabel())) {
	  echo '<input type="checkbox" onclick="return false;" /><span>' . preg_replace('/^use_rbl_/','',$check->getName()) . "&nbsp;&nbsp;";
	  if ($baseconf['REGISTERED'] == '1') {
            echo '<button onclick="window.open(\'https://www.mailcleaner.net/free-trial-options.html\', \'_blank\');">Free Trial</button></span><br />';
          } else {
            echo '<button onclick="window.open(\'https://www.mailcleaner.net/community-edition-add-ons.html\', \'_blank\');">Premium Add-On</button></span><br />';
          }
	} else {
	  echo $this->InputRow($check, array('field_only'=>true,'nobox'=>'true','post_field_text'=>$check->getLabel()."<br />"));
        }
    } ?>
    </td>
    <?php echo $this->InputRow($this->form->getElement('avoidhosts'),array('label_addclass'=>'flabeltextarea'));?>
</tr>

<?php echo $this->InputRow($this->form->getElement('resolve_shorteners'));?>
