<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<td colspan="2">
    <table class="callouttable">
        <?php foreach (['ldapserver', 'basedn', 'binddn', 'bindpass', 'userattribute', 'ldapusessl', 'ldapversion'] as $f) { ?>
            <?php echo $this->InputRow($this->form->getElement($f)); ?>
        <?php } ?>
    </table>
</td>
