<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright 2009, Olivier Diserens
 */
?>
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>" id="<?php echo $this->form->getId()?>">
 <fieldset id="filter">
<div class="addressselectpanel">
    <p><?php echo $this->t->_('Address displayed')?> : </p>
    <?php echo $this->InputRow($this->form->getElement('search'),array('field_only'=>true,'nobox'=>true));?> @ <?php echo $this->InputRow($this->form->getElement('domain'),array('field_only'=>true,'nobox'=>true));?>

  <div class="subadvsearch">
    <div>
    <?php echo $this->InputRow($this->form->getElement('mpp'),array('nobox'=>true));?>
    </div>
    <div class="searchcheckfield">
      <div class="searchcheck">
        <?php echo $this->InputRow($this->form->getElement('forced'),array('nobox'=>true,'field_only'=>true,'post_field_text'=>$this->form->getElement('forced')->getLabel()));?>
      </div>
      <div class="searchcheck">
        <?php echo $this->InputRow($this->form->getElement('hidedup'),array('nobox'=>true,'field_only'=>true,'post_field_text'=>$this->form->getElement('hidedup')->getLabel()));?>
      </div>
      <div class="searchcheck">
        <?php echo $this->InputRow($this->form->getElement('showNewslettersOnly'),array('nobox'=>true,'field_only'=>true,'post_field_text'=>$this->form->getElement('showNewslettersOnly')->getLabel()));?>
      </div>        
    </div>
  </div>
</div>

<div class="searchpanel">
  <div class="searchfields searchsubmit">
    <?php echo $this->SubmitRow($this->form->getElement('submit'));?>
  </div>
  <div class="searchfields">
    <div class="subsearch">
        <img src="<?php echo $this->images_path;?>/loupe.png" alt="<?php echo $this->t->_('search');?>" />
        <?php echo $this->InputRow($this->form->getElement('sender'),array('nobox'=>true));?>
        <?php echo $this->InputRow($this->form->getElement('subject'),array('nobox'=>true));?>
    </div>
    <div class="subsearch">
      <?php echo $this->t->_('From')?> 
      <?php echo $this->InputRow($this->form->getElement('fd'),array('field_only'=>true,'nobox'=>true));?>
      <?php echo $this->InputRow($this->form->getElement('fm'),array('field_only'=>true,'nobox'=>true));?>
      <?php echo $this->t->_('to')?> 
      <?php echo $this->InputRow($this->form->getElement('td'),array('field_only'=>true,'nobox'=>true));?>
      <?php echo $this->InputRow($this->form->getElement('tm'),array('field_only'=>true,'nobox'=>true));?>
    </div>

  </div>
</div>
</fieldset>

</form>

<div id="quarantine">

</div>
