<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright 2009, Olivier Diserens
 */
?>
<div id="generalconfigpanel">
<p class="contentheadicon"><img src="<?php echo $this->images_path?>/config_icon.png" alt="" />&nbsp;</p>
 <p class="contentheadtitle"><?php echo $this->t->_($this->selectedSubMenu)?> : <?php echo $this->t->_('Domains')?></p>

 <div id="domainnavigpanel">
 <?php $user = Zend_Registry::get('user'); ?>
 <?php if ($user && $user->getUserType() == 'administrator') {?>
 <ul id="domainnavoptions">
  <li id="domainoptiontop" class="domainoptiontop" onclick="javascript:loadurl('<?php echo $this->globalurl?>')"><a href="<?php echo $this->globalurl?>"><?php echo $this->t->_('Domain default settings');?></a></li>
  <li class="newdomain" onclick="javascript:loadurl('<?php echo $this->addurl?>')"><span><a href="<?php echo $this->addurl?>"><?php echo $this->t->_('New domain');?></a></span><img src="<?php echo $this->images_path?>/domainaddbutton.png" alt="add" /></li>
 </ul>
 <?php } elseif ($user && $user->getRight('allow_subdomains')) {?>
 <ul id="domainnavoptions">
    <li class="newdomain newdomaintop domainoptiontop" onclick="javascript:loadurl('<?php echo $this->addurl?>')"><span><a href="<?php echo $this->addurl?>"><?php echo $this->t->_('New domain');?></a></span><img src="<?php echo $this->images_path?>/domainaddbutton.png" alt="add" /></li>
  </ul>
 <?php } else {?> 
    <div class="domainnavoptionreplace">&nbsp;</div>
  <?php }?> 
 
 <div id="searchpanel">
 <form id="searchform" action="">
 <p id="searchlabel"><?php echo $this->t->_('Domain specific settings')?></p>
 <div><input type="text" id="sname" value="<?php echo $this->sname?>" /></div>
 </form>
 </div>
 <div id="resultpanel">

<?php echo $this->partial('ajax/domain/search.phtml', array(
                         'domains' => $this->domains,
                         'domainscount' => $this->domainscount,
                         'page' => $this->page,
                         'lastpage' => $this->lastpage,
                         'images_path' => $this->images_path,
                         'sname' => $this->sname,
                         'name' => $this->name,
                         'searchurl' => $this->searchurl,
                         't' => $this->t,
)); ?>
   
 </div>
</div>
 
  <div id="domaincontentpanel">
   <div id="tasksconfigpanel" class="domainconfigpanel">
  
     <h1><img class="importantimg" src="<?php echo $this->images_path?>/warning.png" alt="warning" /><?php echo $this->t->_('Removing domain')?>
           <span class="removedomainlink"><a href="<?php echo $this->backurl?>"><?php echo $this->t->_('Back...')?></a></span>
     </h1>
    <div id="domainalertcontent">
    <h3><?php echo $this->t->_('Domain');?> : <strong><?php echo $this->domain->getParam('name')?></strong></h3>
    <p><?php echo $this->t->_('You are about to remove a domain');?></p>
    <?php if (count($this->domain->getAliases()) > 0) {?>
    <div class="removedomain" id="removedomainonly"><a href="<?php echo $this->removeurldomain;?>"><?php echo $this->t->_('Domain only');?></a></div>
    <div class="removedomain" id="removedomainaliases"><a href="<?php echo $this->removeurlaliases;?>"><?php echo $this->t->_('Domain and all aliases');?></a></div>
    <?php } else {?>
    <div class="removedomain" id="removedomainonly"><a href="<?php echo $this->removeurldomain;?>"><?php echo $this->t->_('Remove domain');?></a></div>
    <?php }?>
    </div>
    
   </div>
 </div>
</div>
