<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>" id="<?php echo $this->form->getId() ?>">
    <?php echo $this->partial('layouts/message.phtml', ['message' => $this->message, 't' => $this->t]); ?>
    <fieldset id="defaultssettings">
        <table class="ftable">
            <?php echo $this->InputRow($this->form->getElement('max_attachments_per_message')); ?>

            <?php echo $this->InputRow(
                $this->form->getElement('max_attach_size'),
                [
                    'post_field_text' =>
                    $this->t->_('bytes') .
                        $this->InputRow(
                            $this->form->getElement('max_attach_size_enable'),
                            [
                                'field_only' => true,
                                'nobox' => true
                            ]
                        ) .
                        $this->InputRow(
                            $this->form->getElement('max_attach_size_enable'),
                            [
                                'label_only' => true,
                                'nobox' => true
                            ]
                        )
                ]
            ); ?>
            <?php echo $this->InputRow(
                $this->form->getElement('max_archive_depth'),
                [
                    'post_field_text' =>
                    $this->InputRow(
                        $this->form->getElement('max_archive_depth_disable'),
                        [
                            'field_only' => true,
                            'nobox' => true
                        ]
                    ) .
                        $this->InputRow(
                            $this->form->getElement('max_archive_depth_disable'),
                            [
                                'label_only' => true,
                                'nobox' => true
                            ]
                        )
                ]
            ); ?>

            <tr>
                <td colspan="2">
                    <hr />
                </td>
            </tr>

            <?php foreach (['expand_tnef', 'deliver_bad_tnef', 'usetnefcontent'] as $f) { ?>
                <?php echo $this->InputRow($this->form->getElement($f)); ?>
            <?php } ?>

            <tr>
                <td colspan="2">
                    <hr />
                </td>
            </tr>

            <?php foreach (['send_notices', 'notices_to'] as $f) { ?>
                <?php echo $this->InputRow($this->form->getElement($f)); ?>
            <?php } ?>

            <?php echo $this->SubmitRow($this->form->getElement('submit')); ?>

        </table>
    </fieldset>
</form>
