<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright 2009, Olivier Diserens
 */
?>
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>" id="<?php echo $this->form->getId()?>">
<?php echo $this->partial('layouts/message.phtml', array('message' => $this->message, 't' => $this->t)); ?>
 <fieldset id="defaultssettings">
       <table class="ftable">
          <?php echo $this->InputRow($this->form->getElement('max_attachments_per_message'));?>
          
          <?php echo $this->InputRow($this->form->getElement('max_attach_size'),array(
               'post_field_text'=>  $this->t->_('bytes') . 
                           $this->InputRow($this->form->getElement('max_attach_size_enable'), array('field_only'=>true,'nobox'=>true)) .
                           $this->InputRow($this->form->getElement('max_attach_size_enable'), array('label_only'=>true,'nobox'=>true))
          
          ));?>
          <?php echo $this->InputRow($this->form->getElement('max_archive_depth'),array(
               'post_field_text'=>  
                           $this->InputRow($this->form->getElement('max_archive_depth_disable'), array('field_only'=>true,'nobox'=>true)) .
                           $this->InputRow($this->form->getElement('max_archive_depth_disable'), array('label_only'=>true,'nobox'=>true))
          
          ));?>
                    
          <tr>
            <td colspan="2"><hr /></td>
          </tr>
          
          <?php foreach (array('expand_tnef', 'deliver_bad_tnef', 'usetnefcontent') as $f) {?>
            <?php echo $this->InputRow($this->form->getElement($f));?>
          <?php }?>
          
          <tr>
            <td colspan="2"><hr /></td>
          </tr>
          
          <?php foreach (array('send_notices', 'notices_to') as $f) {?>
            <?php echo $this->InputRow($this->form->getElement($f));?>
          <?php }?>
          
          <?php echo $this->SubmitRow($this->form->getElement('submit'));?>
          
       </table>
     </fieldset>
 </form>