<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>" id="<?php echo $this->form->getId() ?>">
    <?php echo $this->partial('layouts/message.phtml', ['message' => $this->message, 't' => $this->t]); ?>
    <fieldset id="defaultssettings">
        <table class="ftable">
            <?php echo $this->InputRow($this->form->getElement('silent')); ?>

            <?php echo $this->InputRow($this->form->getElement('scanner_timeout'), ['post_field_text' => $this->t->_('seconds')]); ?>

            <tr>
                <td colspan="2">
                    <hr />
                </td>
            </tr>

            <tr id="subzoneset">
                <td class="flabel"><?php echo $this->t->_('Active scanners') ?> : </td>
                <td class="fvalue">
                    <?php foreach ($this->form->scanners as $s) { ?>
                        <?php echo $s->getParam('comm_name') ?><br />
                    <?php } ?>
                </td>
            </tr>


            <?php echo $this->SubmitRow($this->form->getElement('submit')); ?>

        </table>
    </fieldset>
</form>
