<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright 2009, Olivier Diserens
 */
?>&nbsp;
<?php echo $this->partial('layouts/message.phtml', array('message' => $this->message, 't' => $this->t)); ?>
<fieldset>
       <?php echo $this->InputRow($this->form->getElement('panel'),array('field_only'=>true,'nobox'=>true));?>
       <?php echo $this->InputRow($this->form->getElement('name'),array('field_only'=>true,'nobox'=>true));?>
       <table class="ftable">
       
          <?php foreach (array('language', 'gui_group_quarantines') as $f) {?>
           <?php echo $this->InputRow($this->form->getElement($f));?>
          <?php }?>
          
          <tr>
            <td colspan="2"><hr /></td>
          </tr>
          
           <?php foreach (array('summaryfrequency', 'summary_type', 'summary_to') as $f) {?>
           <?php echo $this->InputRow($this->form->getElement($f));?>
          <?php }?>
          
          <tr>
            <td colspan="2"><hr /></td>
          </tr>
          
           <?php foreach (array('delivery_type', 'spam_tag', 'content_subject', 'file_subject', 'virus_subject') as $f) {?>
           <?php echo $this->InputRow($this->form->getElement($f));?>
          <?php }?>
          
          <?php echo $this->SubmitRow($this->form->getElement('submit'));?>
       </table>
</fieldset>
