<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright 2009, Olivier Diserens
 */
?>
<?php echo $this->partial('layouts/message.phtml', array('message' => $this->message, 't' => $this->t)); ?>
<fieldset>
       <table class="ftable" id="domainaddtable">
      
          <?php echo $this->InputRow($this->form->getElement('defaultvalues'));?>
          <?php echo $this->SubmitRow($this->form->getElement('submit'));?>
       </table>
</fieldset>