<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<?php echo $this->partial('layouts/message.phtml', ['message' => $this->message, 't' => $this->t]); ?>
<fieldset>
    <?php echo $this->InputRow($this->form->getElement('panel'), ['field_only' => true, 'nobox' => true]); ?>
    <?php echo $this->InputRow($this->form->getElement('name'), ['field_only' => true, 'nobox' => true]); ?>
    <table class="ftable">
        <?php echo $this->InputRow($this->form->getElement('servers'), ['label_addclass' => 'flabeltextarea']); ?>

        <?php foreach (['port', 'multipleaction', 'usemx'] as $f) { ?>
            <?php echo $this->InputRow($this->form->getElement($f)); ?>
        <?php } ?>

        <?php echo $this->SubmitRow($this->form->getElement('submit')); ?>
        <tr>
            <td colspan="2">
                <hr />
            </td>
        </tr>
        <?php echo $this->SubmitRow($this->form->getElement('testdestinationSMTP')); ?>
        <tr id="settingstest">
            <td colspan="2"></td>
        </tr>
    </table>
</fieldset>
