<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<?php echo $this->partial('layouts/message.phtml', ['message' => $this->message, 't' => $this->t]); ?>
<fieldset>
    <table class="ftable" id="domainaddtable">

        <?php echo $this->InputRow($this->form->getElement('defaultvalues')); ?>
        <?php echo $this->SubmitRow($this->form->getElement('submit')); ?>
    </table>
</fieldset>
