<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright (C) 2004-2014 Olivier Diserens <olivier@diserens.ch>
 *		  2015-2017 Mentor Reka <reka.mentor@gmail.com>
 */
?>
<?php echo $this->partial('layouts/message.phtml', array('message' => $this->message, 't' => $this->t)); ?>
       <?php echo $this->InputRow($this->form->getElement('panel'),array('field_only'=>true,'nobox'=>true));?>
       <?php echo $this->InputRow($this->form->getElement('name'),array('field_only'=>true,'nobox'=>true));?>
<table class="ftable">
        <tr>
                <td class='flabel'>Administrator(s):</td>
                <td class='fvalue'>
                        <?php if (empty($this->domain->getAdmin()) || $this->domain->getAdmin() == NULL) echo "<div><i> no administrator defined for this domain</i></div>"; ?>
                        <?php foreach ($this->domain->getAdmin() as $admin) {?>
                                <div>
					<?php $user = Zend_Registry::get('user'); ?>
					<?php if ($user && $user->getUserType() == 'administrator') {?>
						<a href='/admin/accesses/edit/sname//page/1/username/<?php echo $admin->username?>'>
					<?php } ?>
					<?php echo $admin->username; ?><?php if ($admin->can_manage_domains != "1" && $admin->can_manage_host != "1") echo " (hotline)"; ?>
					<?php if ($user && $user->getUserType() == 'administrator') {?>
                                                </a>
                                        <?php } ?>
				</div>
                        <?php }?>
                </td>
        </tr>
        <tr><td colspan="2"><hr /></td></tr>
	
        <?php if ($this->domain->getParam('name') != '__global__') {?>
          <?php foreach (array('aliases') as $f) {?>
           <?php echo $this->InputRow($this->form->getElement($f),array('label_addclass'=>'flabeltextarea'));?>
          <?php }?>
          <tr><td colspan="2"><hr /></td></tr>
        <?php }?>      
          <?php foreach (array('systemsender', 'falseneg_to', 'falsepos_to') as $f) {?>
           <?php echo $this->InputRow($this->form->getElement($f));?>
          <?php }?>
          
           <tr><td colspan="2"><hr /></td></tr>
          
          <?php foreach (array('supportname', 'supportemail') as $f) {?>
           <?php echo $this->InputRow($this->form->getElement($f));?>
          <?php }?>
          <?php echo $this->SubmitRow($this->form->getElement('submit'));?>
       </table>
