<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<?php echo $this->partial('layouts/message.phtml', ['message' => $this->message, 't' => $this->t]); ?>
<?php
$connector = $this->domain->getAuthConnector();
if ($this->request->isPost() && $this->request->getParam('connector') && $this->form->getMessages()) {
    $connector = $this->request->getParam('connector');
}
?>
<fieldset>
    <?php echo $this->InputRow($this->form->getElement('panel'), ['field_only' => true, 'nobox' => true]); ?>
    <?php echo $this->InputRow($this->form->getElement('name'), ['field_only' => true, 'nobox' => true]); ?>
    <table class="ftable">
        <?php echo $this->InputRow($this->form->getElement('connector')); ?>
        <tr id="connectorform">
            <?php echo $this->partial('forms/domain/userauthentication/' . strtolower($connector) . 'Form.phtml', ['form' => $this->form, 't' => $this->t, 'message' => $this->message, 'domain' => $this->domain, 'images_path' => $this->images_path]); ?>
        </tr>

        <tr>
            <td colspan="2">
                <hr />
            </td>
        </tr>
        <?php foreach (['usernameformat', 'addresslookup'] as $f) { ?>
            <?php echo $this->InputRow($this->form->getElement($f)); ?>
        <?php } ?>
        <?php echo $this->SubmitRow($this->form->getElement('submit')); ?>

        <tr>
            <td colspan="2">
                <hr />
            </td>
        </tr>
        <?php foreach (['testusername', 'testpassword'] as $f) { ?>
            <?php echo $this->InputRow($this->form->getElement($f)); ?>
        <?php } ?>
        <?php echo $this->SubmitRow($this->form->getElement('testuserauth')); ?>
        <tr id="settingstestwaitingtr">
            <td colspan="2" id="settingstestwaiting"></td>
        </tr>
        <tr id="settingstest">
            <td colspan="2"></td>
        </tr>

    </table>
</fieldset>
