<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 */
?>
<p></p>
<p></p>
<fieldset id="freetrial">
    <table class="ftable">
        <tr>
            <td colspan="2">
                <p style="font-size:14px"><strong>Register as an Enterprise Edition:</strong></p>
            </td>
        </tr>
        <tr>
            <td colspan="2">See the "Register Enterprise Edition" section below to find out the list of main unlocked features</td>
        </tr>
        <tr>
            <td colspan="2" align="center"><a class="notunderlined" href="https://www.mailcleaner.net/trial-request.html?key=Tx3kshaf7324fdD0!" target="_blank"><input type="button" class="linkrebuttonnobold" value="Enterprise Edition Trial" /></a></td>
        </tr>
    </table>
</fieldset>
