<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright 2009, Olivier Diserens
 */
?>
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>" id="<?php echo $this->form->getId()?>">
 
<?php echo $this->partial('layouts/message.phtml', array('message' => $this->message, 't' => $this->t)); ?>
<fieldset id="localesettings">
       <table class="ftable">
          <?php echo $this->InputRow($this->form->getElement('zone'));?>
          <tr id="subzonesetwaiting"><td colspan="2" class="fwaiting"><img src="<?php echo $this->images_path?>/loadingwhitebg.gif" alt="loading..." /></td></tr>
          <?php echo $this->InputRow($this->form->getElement('selectsubzone'), array('row_id'=>'subzoneset'));?>
          <?php echo $this->SubmitRow($this->form->getElement('localesubmit'));?>
       </table>
     </fieldset>
 </form>