<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
$this->form->setTranslator($this->t);
?>
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>" id="<?php echo $this->form->getId() ?>">
    <?php echo $this->partial('layouts/message.phtml', ['message' => $this->message, 't' => $this->t]); ?>
    <fieldset id="companysettings">
        <table class="ftable numberfieldtable">

            <?php echo $this->InputRow(
                $this->form->getElement('smtp_receive_timeout'),
                [
                    'post_field_text' => $this->t->_('seconds')
                ]
            ); ?>
            <?php echo $this->InputRow($this->form->getElement('max_rcpt'), []); ?>


            <tr>
                <td class="flabel"><?php echo $this->t->_('Maximum simultaneous connections') ?> : </td>
                <td class="fvalue"></td>
            </tr>

            <?php foreach (['smtp_accept_max', 'smtp_accept_max_per_host', 'smtp_accept_max_per_trusted_host'] as $f) { ?>
                <?php echo $this->InputRow($this->form->getElement($f)); ?>
            <?php } ?>
            <?php foreach (['smtp_accept_max_per_connection'] as $f) { ?>
                <?php echo $this->InputRow($this->form->getElement($f)); ?>
            <?php } ?>
            <tr>
                <td colspan="2">
                    <hr class="sectionsplit" />
                </td>
            </tr>

            <?php foreach (['smtp_reserve', 'smtp_load_reserve'] as $f) { ?>
                <?php echo $this->InputRow($this->form->getElement($f)); ?>
            <?php } ?>

            <?php echo $this->InputRow(
                $this->form->getElement('global_msg_max_size'),
                [
                    'post_field_text' => $this->t->_('KB')
                ]
            ); ?>
            <?php echo $this->InputRow($this->form->getElement('errors_reply_to')); ?>

            <tr>
                <td colspan="2">
                    <hr />
                </td>
            </tr>
            <tr>
                <td colspan="2" class="fsingle">
                    <?php echo $this->t->_('Sending retries') ?> :
                    <?php echo $this->t->_('every') ?>
                    <?php echo $this->InputRow($this->form->getElement('retry_delay_value'), ['field_only' => true, 'nobox' => true]); ?>
                    <?php echo $this->InputRow($this->form->getElement('retry_delay_unit'), ['field_only' => true, 'nobox' => true]); ?>
                    <?php echo $this->t->_('up to') ?>
                    <?php echo $this->InputRow($this->form->getElement('retry_cutoff_value'), ['field_only' => true, 'nobox' => true]); ?>
                    <?php echo $this->InputRow($this->form->getElement('retry_cutoff_unit'), ['field_only' => true, 'nobox' => true]); ?>
                </td>
            </tr>

            <?php foreach (['rate', 'trusted_rate'] as $rtype) { ?>
                <tr>
                    <td colspan="2">
                        <hr />
                    </td>
                </tr>
                <?php echo $this->InputRow($this->form->getElement($rtype . 'limit_enable')); ?>

                <tr id="<?php echo $rtype ?>_rule_row" class="<?php echo $this->rate_display_class[$rtype] ?>">
                    <td colspan="2" class="fsingle">
                        <?php echo $this->t->_('Incoming per host connection rate limit') ?> :
                        <?php echo $this->InputRow($this->form->getElement($rtype . '_count'), ['field_only' => true, 'nobox' => true]); ?>
                        <?php echo $this->t->_('connections per ') ?>
                        <?php echo $this->InputRow($this->form->getElement($rtype . '_interval_value'), ['field_only' => true, 'nobox' => true]); ?>
                        <?php echo $this->InputRow($this->form->getElement($rtype . '_interval_unit'), ['field_only' => true, 'nobox' => true]); ?>
                    </td>
                </tr>
                <?php echo $this->InputRow(
                    $this->form->getElement($rtype . 'limit_delay'),
                    [
                        'row_id' => $rtype . "_delay_row",
                        'row_class' => $this->rate_display_class[$rtype],
                        'post_field_text' => $this->t->_('seconds')
                    ]
                ); ?>
            <?php } ?>
            <?php echo $this->InputRow($this->form->getElement('no_ratelimit_hosts'), ['row_id' => 'no_ratelimit', 'label_addclass' => 'flabeltextarea']); ?>
            <?php echo $this->SubmitRow($this->form->getElement('submit')); ?>

        </table>
    </fieldset>
</form>
