<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright 2009, Olivier Diserens
 */
?>
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>" id="<?php echo $this->form->getId()?>">
<?php echo $this->partial('layouts/message.phtml', array('message' => $this->message, 't' => $this->t)); ?>
 <fieldset id="companysettings">
       <table id="conncontroltable" class="ftable">
          <?php echo $this->InputRow($this->form->getElement('smtp_conn_access'),array('label_addclass'=>'flabeltextarea'));?>
          <tr>
            <td colspan="2"><hr /></td>
           </tr>
          <?php echo $this->InputRow($this->form->getElement('relay_from_hosts'),array('label_addclass'=>'flabeltextarea'));?>
          <?php echo $this->InputRow($this->form->getElement('allow_relay_for_unknown_domains'));?>
          <?php echo $this->InputRow($this->form->getElement('relay_refused_to_domains'),array('label_addclass'=>'flabeltextarea'));?>
          <tr>
            <td colspan="2"><hr /></td>
           </tr>
          <?php echo $this->InputRow($this->form->getElement('host_reject'),array('label_addclass'=>'flabeltextarea'));?>
          <?php echo $this->InputRow($this->form->getElement('sender_reject'),array('label_addclass'=>'flabeltextarea'));?>
          <?php echo $this->InputRow($this->form->getElement('user_reject'),array('label_addclass'=>'flabeltextarea'));?>
          <?php echo $this->InputRow($this->form->getElement('recipient_reject'),array('label_addclass'=>'flabeltextarea'));?>
          
          <?php echo $this->SubmitRow($this->form->getElement('submit'));?>
          
       </table>
     </fieldset>
 </form>
