<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>" id="<?php echo $this->form->getId() ?>">
    <?php echo $this->partial('layouts/message.phtml', ['message' => $this->message, 't' => $this->t]); ?>
    <fieldset id="taskssettings">
        <table class="ftable">
            <?php foreach (['cron_time', 'cron_weekday', 'cron_monthday'] as $f) { ?>
                <?php echo $this->InputRow($this->form->getElement($f)); ?>
            <?php } ?>

            <?php echo $this->SubmitRow($this->form->getElement('submit')); ?>

        </table>
    </fieldset>
</form>
