<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright 2009, Olivier Diserens
 */
?>
  <h1>An error occurred</h1> 
  <h2><?= $this->message ?></h2> 

  <? if ('development' == APPLICATION_ENV): ?> 
  
  <h3>Exception information:</h3> 
  <p> 
      <b>Message:</b> <?= $this->exception->getMessage() ?> 
  </p> 

  <h3>Stack trace:</h3> 
  <pre><?= $this->exception->getTraceAsString() ?> 
  </pre> 

  <h3>Request Parameters:</h3> 
  <pre><? var_dump($this->request->getParams()) ?> 
  </pre> 
  <? endif ?>