<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<h1>An error occurred</h1>
<h2><?php print($this->message); ?></h2>

<?php if ('development' == APPLICATION_ENV) { ?>

    <h3>Exception information:</h3>
    <p>
        <b>Message:</b> <?php print($this->exception->getMessage()); ?>
    </p>

    <h3>Stack trace:</h3>
    <pre><?php print($this->exception->getTraceAsString()); ?></pre>

    <h3>Request Parameters:</h3>
    <pre><?php print(var_dump($this->request->getParams())); ?></pre>
<?php
}
