#!/usr/bin/perl
#
#   Mailcleaner - SMTP Antivirus/Antispam Gateway
#   Copyright (C) 2021 John Mertz <git@john.me.tz>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#
#   /etc/init.d/clamd: service management for ClamD

use strict;
use warnings;

use lib '/usr/mailcleaner/lib';
use ManageServices;

our $service = 'clamd';

my $manager = ManageServices->new( 'autoStart' => 0 ) || die "Failed to create object: $!\n";
$manager->loadModule($service) || die "Could not load module for service: $service\n";

unless (scalar(@ARGV) && defined($manager->{'module'}->{'actions'}->{$ARGV[0]})) {
	print "\nusage: $0 <action>\n\n";
	$manager->usage($service);
	exit();
}

my $action = shift;

my $status = $manager->{'module'}->{'actions'}->{$action}->{'cmd'}($manager);

if (defined($status) ) {
	print $manager->{'services'}->{$service}->{'name'} . ': ';
	if ($status =~ m/^\-?\d$/) {
		print $manager->{'codes'}->{$status}->{'verbose'} . "\n";
	} else {
		print $status . "\n";
	}
} 
