#! /bin/sh
# /etc/init.d/clamd: start ClamAV daemon.

export PATH=$PATH:/sbin:/usr/sbin

SRCDIR=`grep 'SRCDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
if [ "SRCDIR" = "" ]; then
  SRCDIR=/opt/mailcleaner
fi
VARDIR=`grep 'VARDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
if [ "VARDIR" = "" ]; then
  VARDIR=/var/mailcleaner
fi

DAEMON=/opt/clamav/sbin/clamd
CLAMDDOPTS="--config-file=$SRCDIR/etc/clamav/clamspamd.conf"

chown -R clamav:clamav $VARDIR/log/clamav

prepare () {
  $SRCDIR/bin/dump_mailscanner_config.pl >/dev/null 2>&1
  $SRCDIR/bin/dump_clamav_config.pl >/dev/null 2>&1
}

case "$1" in
  start)
    touch $VARDIR/run/clamspamd.start.rs
    echo -n "  Starting ClamSpam daemon: "
    prepare
    if [ ! -d $VARDIR/spool/clamspam ]; then
      mkdir $VARDIR/spool/clamspam >/dev/null 2>&1
    fi
    DBFILEEXISTS=`ls -l $VARDIR/spool/clamspam/*db 2>&1 | grep 'No such file'`
    #DBFILES=`ls $VARDIR/spool/clamspam/*db 2>&1`
    #if [ "$DBFILES" != "" ]; then
    if [ "$DBFILEEXISTS" = "" ]; then
      $DAEMON $CLAMDDOPTS
      echo "started."
      rm $VARDIR/run/clamspamd.stopped >/dev/null 2>&1
    else 
      echo "no database, not started."
      touch $VARDIR/run/clamspamd.stopped
    fi
    if [ -f $VARDIR/run/clamspamd.rn ]; then
      rm $VARDIR/run/clamspamd.rn
	fi
    rm $VARDIR/run/clamspamd.*.rs >/dev/null 2>&1
    ;;
  stop)
    touch $VARDIR/run/clamspamd.stop.rs
    echo -n "  Stopping ClamSpam daemon: "
    CLAMDPID=`pgrep -f clamspamd.conf`
    if [ ! "$CLAMDPID" = "" ]; then
      kill -KILL $CLAMDPID >/dev/null 2>&1
      sleep 3
    fi
    echo "stopped."
    touch $VARDIR/run/clamspamd.stopped
    rm $VARDIR/run/clamspamd.stop.rs >/dev/null 2>&1
    ;;
  restart|reload|force-reload)
    touch $VARDIR/run/clamspamd.restart.rs
	$0 stop
	sleep 3
	$0 start
    ;;
  *)
    echo "Usage: /etc/init.d/clamspamd {start|stop|restart}"
    exit 1
esac

exit 0
