#! /bin/sh
#
#   Mailcleaner - SMTP Antivirus/Antispam Gateway
#   Copyright (C) 2016 Florian Billebault <florian.billebault@gmail.com>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#
#   /etc/init.d/newsld: start Newsld daemon.

export PATH=$PATH:/sbin:/usr/sbin:/var/tests/newsld/bin

SRCDIR=`grep 'SRCDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
if [ "SRCDIR" = "" ]; then
  SRCDIR=/opt/mailcleaner
fi
VARDIR=`grep 'VARDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
if [ "VARDIR" = "" ]; then
  VARDIR=/var/mailcleaner
fi

prepare () {

OPTIONS="";
for conf in `cat $SRCDIR/etc/mailscanner/newsld.conf`; do
  op=`echo $conf | cut -d'=' -f1`
  val=`echo $conf | cut -d'=' -f2`
  if [ "$op" = "$val" ] || [ "$val" = "yes" ]; then
    OPTIONS=$OPTIONS" --$op"
  else
    if [ "$val" != "no" ]; then
      OPTIONS=$OPTIONS" --$op=$val"
    fi
  fi 
done

DAEMON=/usr/local/bin/newsld
#SPAMDOPTS="-C /usr/local/share/spamassassin/ 
#           --siteconfigpath=$SRCDIR/share/spamassassin 
#           -r $VARDIR/spool/spamassassin/spamd.pid 
#           -s $VARDIR/log/mailscanner/spamd.log
#           -u mailcleaner -g mailcleaner
#           --socketpath=$VARDIR/spool/spamassassin/spamd.sock -d"
export NEWSLDOPTS="$OPTIONS"
}

export TMPDIR=$VARDIR/spool/tmp

case "$1" in
  start)
    touch $VARDIR/run/newsld.start.rs
    echo -n "  Starting Newsld daemon: "
    prepare
    $DAEMON $NEWSLDOPTS >/dev/null 2>&1
    echo "started."
    if [ -f $VARDIR/run/newsld.rn ]; then
      rm $VARDIR/run/newsld.rn
    fi
    rm $VARDIR/run/newsld.stopped >/dev/null 2>&1
    rm $VARDIR/run/newsld.*.rs >/dev/null 2>&1
    ;;
  stop)
    touch $VARDIR/run/newsld.stop.rs
    echo -n "  Stopping Newsld daemon: "
    NEWSLDPID=`pgrep -f newsld.pid`
    if [ ! "$NEWSLDPID" = "" ]; then
      kill -KILL $NEWSLDPID >/dev/null 2>&1
    fi
    for NEWSLDCHILDPID in `pgrep -f 'newsld child'`; do
      kill -KILL $NEWSLDCHILDPID >/dev/null 2>&1
    done
    echo "stopped."
    rm $VARDIR/run/newsld.stop.rs >/dev/null 2>&1
    touch $VARDIR/run/newsld.stopped
    ;;
  restart|reload|force-reload)
    touch $VARDIR/run/newsld.restart.rs
	$0 stop
	sleep 3
	$0 start
    ;;
  status)
    NEWSLDPID=`pgrep -f newsld.pid`
    if [ ! "$NEWSLDPID" = "" ]; then
      echo $(basename $0) is running.
    else
      echo $(basename $0) is stopped.
    fi
    ;;

  *)
    echo "Usage: /etc/init.d/newsld {start|stop|restart|status}"
    exit 1
esac

exit 0
