#!/bin/bash
export PATH=$PATH:/sbin:/usr/sbin

SRCDIR=`grep 'SRCDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
if [ "SRCDIR" = "" ]; then
  SRCDIR=/opt/mailcleaner
fi
VARDIR=`grep 'VARDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
if [ "VARDIR" = "" ]; then
  VARDIR=/var/mailcleaner
fi

DAEMON=$SRCDIR/bin/daemon_starter.pl
DAEMONCLASS=SpamHandler
STARTERCLASS=spamhandler
VISIBLENAME="Spam Handler daemon"

case "$2" in
  -d)
    OPTIONS="-daemonize 0"
    ;;
  *)
    OPTIONS=""
esac

case "$1" in
  start)
    touch $VARDIR/run/$STARTERCLASS.start.rs
    echo -n "  Starting $VISIBLENAME:"
    $DAEMON $DAEMONCLASS $OPTIONS start
    rm $VARDIR/run/$STARTERCLASS.stopped >/dev/null 2>&1
    rm $VARDIR/run/$STARTERCLASS.*.rs >/dev/null 2>&1
    echo "started";
  ;;
  # Testing
  multistart)
    touch $VARDIR/run/$STARTERCLASS.start.rs
    echo -n "  Starting $VISIBLENAME:"
    $DAEMON $DAEMONCLASS $OPTIONS multistart
    rm $VARDIR/run/$STARTERCLASS.stopped >/dev/null 2>&1
    rm $VARDIR/run/$STARTERCLASS.*.rs >/dev/null 2>&1
    echo "started";
  ;;
  stop)
    touch $VARDIR/run/$STARTERCLASS.stop.rs
    echo -n "  Stopping $VISIBLENAME: "
    $DAEMON $DAEMONCLASS $OPTIONS stop
    echo "stopped."
    rm $VARDIR/run/$STARTERCLASS.stop.rs >/dev/null 2>&1
    touch $VARDIR/run/$STARTERCLASS.stopped
  ;;
  restart)
    touch $VARDIR/run/$STARTERCLASS.restart.rs
    echo -n "  Restarting $VISIBLENAME: "
    $DAEMON $DAEMONCLASS $OPTIONS restart
    rm $VARDIR/run/$STARTERCLASS.restart.rs >/dev/null 2>&1
  ;;
  status)
    echo -n "  $VISIBLENAME:"
    $DAEMON $DAEMONCLASS $OPTIONS status
  ;;
  *)
    echo "Usage: $SRCDIR/etc/init.d/$STARTERCLASS {start|stop|restart|status}"
    exit 1
esac

exit 0
