#! /bin/sh
# /etc/init.d/spamd: start SpamAssassin daemon.

export PATH=$PATH:/sbin:/usr/sbin

SRCDIR=`grep 'SRCDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
if [ "SRCDIR" = "" ]; then
  SRCDIR=/opt/mailcleaner
fi
VARDIR=`grep 'VARDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
if [ "VARDIR" = "" ]; then
  VARDIR=/var/mailcleaner
fi

prepare () {
  $SRCDIR/bin/dump_mailscanner_config.pl >/dev/null 2>&1
  /usr/bin/pyzor discover >/dev/null 2>&1

OPTIONS="";
for conf in `cat $SRCDIR/etc/mailscanner/spamd.conf`; do
  op=`echo $conf | cut -d'=' -f1`
  val=`echo $conf | cut -d'=' -f2`
  if [ "$op" = "$val" ] || [ "$val" = "yes" ]; then
    OPTIONS=$OPTIONS" --$op"
  else
    if [ "$val" != "no" ]; then
      OPTIONS=$OPTIONS" --$op=$val"
    fi
  fi 
done

DAEMON=/usr/local/bin/spamd
#SPAMDOPTS="-C /usr/local/share/spamassassin/ 
#           --siteconfigpath=$SRCDIR/share/spamassassin 
#           -r $VARDIR/spool/spamassassin/spamd.pid 
#           -s $VARDIR/log/mailscanner/spamd.log
#           -u mailcleaner -g mailcleaner
#           --socketpath=$VARDIR/spool/spamassassin/spamd.sock -d"
export SPAMDOPTS="$OPTIONS"
}

export TMPDIR=$VARDIR/spool/tmp

if [ -L $SRCDIR/etc/mailscanner/spam.assassin.prefs.conf ]; then 
    ln -s $SRCDIR/etc/mailscanner/spam.assassin.prefs.conf $SRCDIR/share/spamassassin/mailscanner.cf 2>&1 > /dev/null
fi

case "$1" in
  start)
    touch $VARDIR/run/spamd.start.rs
    echo -n "  Starting SpamAssassin daemon: "
    /usr/mailcleaner/bin/dump_custom_spamc_rules.sh
    /usr/mailcleaner/bin/dump_spamc_double_items.pl

    prepare
    $DAEMON $SPAMDOPTS >/dev/null 2>&1
    echo "started."
    if [ -f $VARDIR/run/spamd.rn ]; then
      rm $VARDIR/run/spamd.rn
    fi
    rm $VARDIR/run/spamd.stopped >/dev/null 2>&1
    rm $VARDIR/run/spamd.*.rs >/dev/null 2>&1
    ;;
  stop)
    touch $VARDIR/run/spamd.stop.rs
    echo -n "  Stopping SpamAssassin daemon: "
    SPAMDPID=`pgrep -f spamd.pid`
    if [ ! "$SPAMDPID" = "" ]; then
      kill -KILL $SPAMDPID >/dev/null 2>&1
    fi
    for SPID in `pgrep -f 'spamd child'`; do
      kill -KILL $SPID >/dev/null 2>&1
    done
    echo "stopped."
    rm $VARDIR/run/spamd.stop.rs >/dev/null 2>&1
    touch $VARDIR/run/spamd.stopped
    ;;
  restart|reload|force-reload)
    touch $VARDIR/run/spamd.restart.rs
	$0 stop
	sleep 3
	$0 start
    ;;
  *)
    echo "Usage: /etc/init.d/spamd {start|stop|restart}"
    exit 1
esac

exit 0
