#!/bin/bash
export PATH=$PATH:/sbin:/usr/sbin

SRCDIR=`grep 'SRCDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
if [ "SRCDIR" = "" ]; then
  SRCDIR=/opt/mailcleaner
fi
VARDIR=`grep 'VARDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
if [ "VARDIR" = "" ]; then
  VARDIR=/var/mailcleaner
fi

ACTION=$1
DAEMON=$SRCDIR/bin/daemon_starter.pl
DAEMONCLASS=SpamHandler
STARTERCLASS=spamhandler
VISIBLENAME="Spam Handler daemon"

check_lockfile () {
    for STATE in start stop restart; do
        if [ -f $VARDIR/run/$STARTERCLASS.$STATE.rs ]; then
            echo "failed to $ACTION."
            echo "  Init locked: already running $STATE ($VARDIR/run/$STARTERCLASS.$STATE.rs)"
            exit
        fi
    done
}

case "$2" in
  -d)
    OPTIONS="-daemonize 0"
    ;;
  *)
    OPTIONS=""
esac

case "$1" in
  start)
    echo -n "  Starting $VISIBLENAME: "
    check_lockfile
    touch $VARDIR/run/$STARTERCLASS.start.rs
    $DAEMON $DAEMONCLASS $OPTIONS start
    rm $VARDIR/run/$STARTERCLASS.start.rs >/dev/null 2>&1
  ;;
  # Testing
  multistart)
    touch $VARDIR/run/$STARTERCLASS.starting.rs
    echo -n "  Starting $VISIBLENAME: "
    $DAEMON $DAEMONCLASS $OPTIONS multistart
    rm $VARDIR/run/$STARTERCLASS.stopped >/dev/null 2>&1
    rm $VARDIR/run/$STARTERCLASS.*.rs >/dev/null 2>&1
  ;;
  stop)
    echo -n "  Stopping $VISIBLENAME: "
    check_lockfile
    touch $VARDIR/run/$STARTERCLASS.stop.rs
    $DAEMON $DAEMONCLASS $OPTIONS stop
    rm $VARDIR/run/$STARTERCLASS.pid >/dev/null 2>&1
    rm $VARDIR/run/$STARTERCLASS.stop.rs >/dev/null 2>&1
  ;;
  restart)
    echo -n "  Stopping $VISIBLENAME: "
    check_lockfile
    touch $VARDIR/run/$STARTERCLASS.restart.rs
    $DAEMON $DAEMONCLASS $OPTIONS stop
    rm $VARDIR/run/$STARTERCLASS.pid >/dev/null 2>&1
    echo -n "  Starting $VISIBLENAME: "
    $DAEMON $DAEMONCLASS $OPTIONS start
    rm $VARDIR/run/$STARTERCLASS.restart.rs >/dev/null 2>&1
  ;;
  status)
    echo -n "  $VISIBLENAME: "
    check_lockfile
    $DAEMON $DAEMONCLASS $OPTIONS status
  ;;
  *)
    echo "Usage: $SRCDIR/etc/init.d/$STARTERCLASS {start|stop|restart|status}"
    exit 1
esac

exit 0
