#! /bin/sh


export PATH=$PATH:/sbin:/usr/sbin

SRCDIR=`grep 'SRCDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
if [ "SRCDIR" = "" ]; then
  SRCDIR=/opt/mailcleaner
fi
VARDIR=`grep 'VARDIR' /etc/mailcleaner.conf | cut -d ' ' -f3`
if [ "VARDIR" = "" ]; then
  VARDIR=/var/mailcleaner
fi

DAEMON=$SRCDIR/bin/daemon_starter.pl
DAEMONCLASS=StatsDaemon
STARTERCLASS=statsdaemon
VISIBLENAME="Statistics daemon"

case "$2" in
  -d)
    OPTIONS="-daemonize 0 -debug 1"
    ;;
  *)
    OPTIONS=""
esac

case "$1" in
  start)
    touch $VARDIR/run/$STARTERCLASS.start.rs
    echo -n "  Starting $VISIBLENAME: "
    $DAEMON $DAEMONCLASS $OPTIONS start
    echo "started."
    rm $VARDIR/run/$STARTERCLASS.stopped >/dev/null 2>&1
    rm $VARDIR/run/$STARTERCLASS.*.rs >/dev/null 2>&1
    
  ;;
  stop)
    touch $VARDIR/run/$STARTERCLASS.stop.rs
    echo -n "  Stopping $VISIBLENAME: "
    $DAEMON $DAEMONCLASS $OPTIONS stop
    echo "stopped."
    rm $VARDIR/run/$STARTERCLASS.stop.rs >/dev/null 2>&1
    touch $VARDIR/run/$STARTERCLASS.stopped
  ;;
  stopall)
    touch $VARDIR/run/$STARTERCLASS.stop.rs
    echo -n "  Stopping $VISIBLENAME: "
    $DAEMON $DAEMONCLASS $OPTIONS stopall
    echo "stopped."
    rm $VARDIR/run/$STARTERCLASS.stop.rs >/dev/null 2>&1
    touch $VARDIR/run/$STARTERCLASS.stopped
  ;;
  restart)
    touch $VARDIR/run/$STARTERCLASS.restart.rs
    echo -n "  Restarting $VISIBLENAME: "
    $DAEMON $DAEMONCLASS $OPTIONS restart
    echo "restarted."
    rm $VARDIR/run/$STARTERCLASS.restart.rs >/dev/null 2>&1
  ;;
  status)
    $DAEMON $DAEMONCLASS $OPTIONS status
  ;;
  *)
    echo "Usage: $SRCDIR/etc/init.d/$STARTERCLASS {start|stop|stopall|restart|status}"
    exit 1
esac

exit 0
  
