<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<div id="generalconfigpanel">
    <p class="contentheadicon"><img src="<?php echo $this->images_path ?>/config_icon.png" alt="" />&nbsp;</p>
    <p class="contentheadtitle"><?php echo $this->t->_($this->selectedSubMenu) ?> : <?php echo $this->t->_('Administrators') ?></p>

    <div id="domainnavigpanel">
        <ul id="domainnavoptions">
            <li class="domainoptiontop newdomain newdomainselected" onclick="javascript:loadurl('<?php echo $this->addurl ?>')"><span><a href="<?php echo $this->addurl ?>"><?php echo $this->t->_('New administrator'); ?></a></span><img src="<?php echo $this->images_path ?>/domainaddbuttonselected.png" alt="add" /></li>
        </ul>

        <div id="searchpanel">
            <form id="searchform" action="">
                <p id="searchlabel"><?php echo $this->t->_('Administrator specific settings') ?></p>
                <div><input type="text" id="sname" value="<?php echo $this->sname ?>" /></div>
            </form>
        </div>
        <div id="resultpanel">
            <?php echo $this->partial(
                'ajax/accesses/search.phtml',
                [
                    'admins' => $this->admins,
                    'adminscount' => $this->adminscount,
                    'page' => $this->page,
                    'lastpage' => $this->lastpage,
                    'images_path' => $this->images_path,
                    'sname' => $this->sname,
                    'username' => $this->username,
                    'searchurl' => $this->searchurl,
                    't' => $this->t,
                ]
            ); ?>
        </div>
    </div>

    <div id="domaincontentpanel">
        <div id="adminconfigpanel" class="domainconfigpanel">
            <?php echo $this->partial('layouts/message.phtml', ['message' => $this->message, 't' => $this->t]); ?>
            <form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>" id="<?php echo $this->form->getId() ?>">
                <?php echo $this->InputRow($this->form->getElement('username'), ['field_only' => true, 'nobox' => true]); ?>
                <h1 class="adddomaincontentpaneltitle"><?php echo $this->t->_('Administrator name'); ?> : <?php echo $this->InputRow($this->form->getElement('newusername'), ['field_only' => true, 'nobox' => true]); ?></h1>

                <?php echo $this->partial('forms/admineditForm.phtml', ['form' => $this->form, 't' => $this->t, 'message' => $this->message, 'admin' => $this->admin, 'images_path' => $this->images_path]); ?>

            </form>

        </div>
    </div>

</div>
