<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright 2009, Olivier Diserens
 */
?>
<div id="generalconfigpanel">
  <p class="contentheadicon"><img src="<?php echo $this->images_path?>/config_icon.png" alt="" />&nbsp;</p>
  <p class="contentheadtitle"><?php echo $this->t->_($this->selectedSubMenu)?> : <?php echo $this->t->_('Administrators')?></p>

  <div id="domainnavigpanel">
    <ul id="domainnavoptions">
      <li class="domainoptiontop" onclick="javascript:loadurl('<?php echo $this->addurl?>')"><span><a href="<?php echo $this->addurl?>"><?php echo $this->t->_('New administrator');?></a></span><img src="<?php echo $this->images_path?>/domainaddbutton.png" alt="add" /></li>
    </ul>
 
    <div id="searchpanel">
      <form id="searchform" action="">
        <p id="searchlabel"><?php echo $this->t->_('Administrator specific settings')?></p>
        <div><input type="text" id="sname" value="<?php echo $this->sname?>" /></div>
      </form>
    </div>
    <div id="resultpanel">
<?php echo $this->partial('ajax/accesses/search.phtml', array(
                         'admins' => $this->admins,
                         'adminscount' => $this->adminscount,
                         'page' => $this->page,
                         'lastpage' => $this->lastpage,
                         'images_path' => $this->images_path,
                         'sname' => $this->sname,
                         'username' => $this->username,
                         'searchurl' => $this->searchurl,
                         't' => $this->t,
)); ?>   
    </div>
  </div>
 
  <div id="domaincontentpanel">
    <div id="adminconfigpanel" class="domainconfigpanel">
  
    <p class="descmessage"><?php echo $this->t->_('Please select or add an administrator using the navigation panel on the left')?>.</p>
 <?php echo $this->partial('layouts/message.phtml', array('message' => $this->message, 't' => $this->t)); ?>
    </div>
  </div>
 
</div>
