<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<?php echo $this->partial('forms/domain/userauthentication/' . strtolower($this->connector) . 'Form.phtml', ['form' => $this->form, 't' => $this->t, 'message' => $this->message, 'domain' => $this->domain]); ?>
