<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>" id="<?php echo $this->form->getId() ?>">
    <fieldset id="filter">

        <div class="searchpanel contentsearchpanel">
            <div class="searchfields">
                <div class="subsearch subsearchdate">
                    <img src="<?php echo $this->images_path; ?>/loupe.png" alt="<?php echo $this->t->_('search'); ?>" />
                    <?php echo $this->t->_('Date') ?>
                    <?php echo $this->InputRow($this->form->getElement('fd'), ['field_only' => true, 'nobox' => true]); ?>
                    <?php echo $this->InputRow($this->form->getElement('fm'), ['field_only' => true, 'nobox' => true]); ?>
                    <?php echo $this->SubmitRow($this->form->getElement('submit')); ?>
                </div>

            </div>
        </div>
    </fieldset>

</form>


<div id="logsbloc" class='stats'>

</div>
