<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<fieldset>
    <table class="ftable">
        <?php echo $this->InputRow($this->form->getElement('delivery_type')); ?>
        <?php echo $this->InputRow($this->form->getElement('spam_tag'), ['row_class' => 'spam_tag_row']); ?>

        <tr>
            <td colspan="2">
                <hr />
            </td>
        </tr>

        <?php echo $this->InputRow($this->form->getElement('quarantine_bounces')); ?>

        <tr>
            <td colspan="2">
                <hr />
            </td>
        </tr>

        <?php foreach (['frequency', 'summary_type', 'summary_to'] as $f) { ?>
            <?php echo $this->InputRow($this->form->getElement($f)); ?>
        <?php } ?>

        <tr>
            <td colspan="2">
                <hr />
            </td>
        </tr>
        <?php echo $this->InputRow($this->form->getElement('bypass_filtering')); ?>

        <?php echo $this->SubmitRow($this->form->getElement('submit')); ?>
    </table>
</fieldset>
