<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>&nbsp;
<fieldset>
    <table class="ftable">
        <?php if ($this->form->canArchive()) {
            echo $this->InputRow($this->form->getElement('archive_mail')); ?>
            <tr>
                <td colspan="2">
                    <hr />
                </td>
            </tr>
        <?php  } ?>

        <?php echo $this->InputRow($this->form->getElement('copyto_mail')); ?>

        <?php echo $this->SubmitRow($this->form->getElement('submit')); ?>
    </table>
</fieldset>
