<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<fieldset>
    <table class="ftable">

        <?php echo $this->InputRow($this->form->getElement('language')); ?>

        <?php echo $this->SubmitRow($this->form->getElement('submit')); ?>

    </table>
</fieldset>
