USE mc_config;

DROP TABLE IF EXISTS user_pref;

CREATE TABLE user_pref (
  id                             int NOT NULL auto_increment,
  viruswall                      bool NOT NULL DEFAULT '1',
  spamwall                       bool NOT NULL DEFAULT '1',
  block_bad_tnef                 bool NOT NULL DEFAULT '0',
  block_encrypted                bool NOT NULL DEFAULT '0', 
  block_unencrypted              bool NOT NULL DEFAULT '0', 
  allow_passprotected_archives   bool NOT NULL DEFAULT '0', 
  allow_partial                  bool NOT NULL DEFAULT '0', 
  allow_external_bodies          bool NOT NULL DEFAULT '0', 
  allow_iframe                   bool NOT NULL DEFAULT '0', 
  allow_forms                    bool NOT NULL DEFAULT '1',
  allow_scripts                  bool NOT NULL DEFAULT '0', 
  allow_codebase                 bool NOT NULL DEFAULT '0', 
  convert_danger_to_text         bool NOT NULL DEFAULT '0', 
  convert_html_to_text           bool NOT NULL DEFAULT '0', 
  notify_sender                  bool NOT NULL DEFAULT '1', 
  notify_virus_sender            bool NOT NULL DEFAULT '0', 
  notify_blocked_sender          bool NOT NULL DEFAULT '1', 
  notify_blocked_content         bool NOT NULL DEFAULT '1',
  virus_modify_subject           bool NOT NULL DEFAULT '1', 
  virus_subject                  varchar(20) NOT NULL DEFAULT '{Virus?}',
  file_modify_subject            bool NOT NULL DEFAULT '1', 
  file_subject                   varchar(20) NOT NULL DEFAULT '{Virus?}',
  content_modify_subject         bool NOT NULL DEFAULT '1', 
  content_subject                varchar(20) NOT NULL DEFAULT '{Virus?}',
  warning_attach                 bool NOT NULL DEFAULT '1', 
  warning_filename               varchar(50) NOT NULL DEFAULT 'AttentionVirus.txt',
  warning_encoding_charset       varchar(20) NOT NULL DEFAULT 'ISO-8859-1',
  use_bayes                      bool NOT NULL DEFAULT '1',
  ok_languages                   varchar(50) NOT NULL DEFAULT 'fr en de it es',
  ok_locales                     varchar(50) NOT NULL DEFAULT 'fr en de it es',
  use_rbls                       bool NOT NULL DEFAULT '1',
  use_dcc                        bool NOT NULL DEFAULT '1',
  use_razor                      bool NOT NULL DEFAULT '1',
  use_pyzor                      bool NOT NULL DEFAULT '1',
  delivery_type                  int NOT NULL DEFAULT  '1',
  daily_summary                  bool NOT NULL DEFAULT '0',
  weekly_summary                 bool NOT NULL DEFAULT '1', 
  monthly_summary                bool NOT NULL DEFAULT '0',
  summary                        bool NOT NULL DEFAULT '1',
  summary_freq                   int NOT NULL DEFAULT  '1',
  summary_type                   varchar(20) NOT NULL DEFAULT 'NOTSET',
  summary_to                     varchar(200),
  spam_tag                       varchar(20) NOT NULL DEFAULT '{Spam?}',
  quarantine_bounces 		 bool NOT NULL DEFAULT '0',
  has_whitelist				   bool NOT NULL DEFAULT '0',
  has_warnlist				   bool NOT NULL DEFAULT '0',
  has_blacklist                             bool NOT NULL DEFAULT '0',
  language                       varchar(5) NOT NULL DEFAULT 'fr',
  gui_displayed_spams			  int NOT NULL DEFAULT '20',
  gui_displayed_days             int NOT NULL DEFAULT '7',
  gui_mask_forced                bool NOT NULL DEFAULT '0',
  gui_default_address            varchar(200) DEFAULT '',
  gui_graph_type                 varchar(20) NOT NULL DEFAULT 'bar',
  gui_group_quarantines          bool NOT NULL DEFAULT '0',
  archive_mail                   bool NOT NULL DEFAULT '0',
  archive_spam                   bool NOT NULL DEFAULT '0',
  copyto_mail                    varchar(250) DEFAULT '',
  bypass_filtering               bool NOT NULL DEFAULT '0',
  allow_newsletters              tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id)
);

-- create default preferences set
INSERT INTO user_pref SET id=1;
