USE mc_config;

DROP TABLE IF EXISTS user_pref;

CREATE TABLE user_pref (
  id                             int(11) NOT NULL auto_increment,
  viruswall                      tinyint(1) NOT NULL DEFAULT '1',
  spamwall                       tinyint(1) NOT NULL DEFAULT '1',
  block_bad_tnef                 tinyint(1) NOT NULL DEFAULT '0',
  block_encrypted                tinyint(1) NOT NULL DEFAULT '0', 
  block_unencrypted              tinyint(1) NOT NULL DEFAULT '0', 
  allow_passprotected_archives   tinyint(1) NOT NULL DEFAULT '0', 
  allow_partial                  tinyint(1) NOT NULL DEFAULT '0', 
  allow_external_bodies          tinyint(1) NOT NULL DEFAULT '0', 
  allow_iframe                   tinyint(1) NOT NULL DEFAULT '0', 
  allow_forms                    tinyint(1) NOT NULL DEFAULT '1',
  allow_scripts                  tinyint(1) NOT NULL DEFAULT '0', 
  allow_codebase                 tinyint(1) NOT NULL DEFAULT '0', 
  convert_danger_to_text         tinyint(1) NOT NULL DEFAULT '0', 
  convert_html_to_text           tinyint(1) NOT NULL DEFAULT '0', 
  notify_sender                  tinyint(1) NOT NULL DEFAULT '1', 
  notify_virus_sender            tinyint(1) NOT NULL DEFAULT '0', 
  notify_blocked_sender          tinyint(1) NOT NULL DEFAULT '1', 
  notify_blocked_content         tinyint(1) NOT NULL DEFAULT '1',
  virus_modify_subject           tinyint(1) NOT NULL DEFAULT '1', 
  virus_subject                  varchar(20) NOT NULL DEFAULT '{Virus?}',
  file_modify_subject            tinyint(1) NOT NULL DEFAULT '1', 
  file_subject                   varchar(20) NOT NULL DEFAULT '{Virus?}',
  content_modify_subject         tinyint(1) NOT NULL DEFAULT '1', 
  content_subject                varchar(20) NOT NULL DEFAULT '{Virus?}',
  warning_attach                 tinyint(1) NOT NULL DEFAULT '1', 
  warning_filename               varchar(50) NOT NULL DEFAULT 'AttentionVirus.txt',
  warning_encoding_charset       varchar(20) NOT NULL DEFAULT 'ISO-8859-1',
  use_bayes                      tinyint(1) NOT NULL DEFAULT '1',
  ok_languages                   varchar(50) NOT NULL DEFAULT 'fr en de it es',
  ok_locales                     varchar(50) NOT NULL DEFAULT 'fr en de it es',
  use_rbls                       tinyint(1) NOT NULL DEFAULT '1',
  use_dcc                        tinyint(1) NOT NULL DEFAULT '1',
  use_razor                      tinyint(1) NOT NULL DEFAULT '1',
  use_pyzor                      tinyint(1) NOT NULL DEFAULT '1',
  delivery_type                  int(11) NOT NULL DEFAULT  '1',
  daily_summary                  tinyint(1) NOT NULL DEFAULT '0',
  weekly_summary                 tinyint(1) NOT NULL DEFAULT '1', 
  monthly_summary                tinyint(1) NOT NULL DEFAULT '0',
  summary                        tinyint(1) NOT NULL DEFAULT '1',
  summary_freq                   int(11) NOT NULL DEFAULT  '1',
  summary_type                   varchar(20) NOT NULL DEFAULT 'NOTSET',
  summary_to                     varchar(200),
  spam_tag                       varchar(20) NOT NULL DEFAULT '{Spam?}',
  quarantine_bounces 		 tinyint(1) NOT NULL DEFAULT '0',
  has_whitelist                  tinyint(1) NOT NULL DEFAULT '0',
  has_warnlist                   tinyint(1) NOT NULL DEFAULT '0',
  has_blacklist                  tinyint(1) NOT NULL DEFAULT '0',
  language                       varchar(4) NOT NULL DEFAULT 'fr',
  gui_displayed_spams            int(11) NOT NULL DEFAULT '20',
  gui_displayed_days             int(11) NOT NULL DEFAULT '7',
  gui_mask_forced                tinyint(1) NOT NULL DEFAULT '0',
  gui_default_address            varchar(200) DEFAULT '',
  gui_graph_type                 varchar(20) NOT NULL DEFAULT 'bar',
  gui_group_quarantines          tinyint(1) NOT NULL DEFAULT '0',
  archive_mail                   tinyint(1) NOT NULL DEFAULT '0',
  archive_spam                   tinyint(1) NOT NULL DEFAULT '0',
  copyto_mail                    varchar(250) DEFAULT '',
  bypass_filtering               tinyint(1) NOT NULL DEFAULT '0',
  allow_newsletters              tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (id)
);

-- create default preferences set
INSERT INTO user_pref SET id=1;
