<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright 2009, Olivier Diserens
 */
?>
<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>" id="<?php echo $this->form->getId()?>">
 <fieldset id="filter">
<div class="addressselectpanel">
    <?php echo $this->t->_('Local address')?> :
    <?php echo $this->InputRow($this->form->getElement('search'),array('field_only'=>true,'nobox'=>true));?> @ <?php echo $this->InputRow($this->form->getElement('domain'),array('field_only'=>true,'nobox'=>true));?>

  <div class="subadvsearch">
    <div>
    <?php echo $this->InputRow($this->form->getElement('mpp'),array('nobox'=>true));?>
    </div>
    <div class="searchcheckfield">
      <div class="searchcheck">
        <?php echo $this->InputRow($this->form->getElement('hiderejected'),array('nobox'=>true,'field_only'=>true,'post_field_text'=>$this->form->getElement('hiderejected')->getLabel()));?>
      </div>
    </div>

   </div>
</div>

<div class="searchpanel contentsearchpanel">
  <div class="searchfields searchsubmit">
    <?php echo $this->SubmitRow($this->form->getElement('submit'));?>
  </div>
  <div class="searchfields">
    <div class="subsearch">
        <img src="<?php echo $this->images_path;?>/loupe.png" alt="<?php echo $this->t->_('search');?>" />
	  <?php echo $this->InputRow($this->form->getElement('sender'),array('nobox'=>true));?>
    </div>
    <div class="subsearch">
    <?php echo $this->t->_('Date selection')?> : 
      <?php echo $this->t->_('From')?> 
      <?php echo $this->InputRow($this->form->getElement('fd'),array('field_only'=>true,'nobox'=>true));?>
      <?php echo $this->InputRow($this->form->getElement('fm'),array('field_only'=>true,'nobox'=>true));?>
      <?php echo $this->t->_('to')?> 
      <?php echo $this->InputRow($this->form->getElement('td'),array('field_only'=>true,'nobox'=>true));?>
      <?php echo $this->InputRow($this->form->getElement('tm'),array('field_only'=>true,'nobox'=>true));?>
    </div>

  </div>
</div>
</fieldset>

</form>

<div id="tracinglog">
<p class="descmessage"><?php echo $this->t->_('Please select search parameters in the filter panel above')?>.</p>
</div>
