<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<div id="generalconfigpanel">
    <p class="contentheadicon"><img src="<?php echo $this->images_path ?>/config_icon.png" alt="" />&nbsp;</p>
    <p class="contentheadtitle"><?php echo $this->t->_($this->selectedSubMenu) ?> : <?php echo $this->t->_('Users') ?></p>

    <div id="domainnavigpanel">
        <div id="searchpanel" class="addbutton">
            <form method="<?php echo $this->searchForm->getMethod() ?>" action="<?php echo $this->searchForm->getAction() ?>" id="<?php echo $this->searchForm->getId() ?>">
                <p id="searchlabel"><?php echo $this->t->_('Search by') ?> : <?php echo $this->InputRow($this->searchForm->getElement('type'), ['field_only' => true, 'nobox' => true]); ?></p>
                <p id="usersearchlabel"><?php echo $this->t->_('Enter username and select domain') ?> : </p>
                <p id="emailsearchlabel"><?php echo $this->t->_('Enter email address') ?> : </p>
                <p>
                    <?php echo $this->inputRow($this->searchForm->getElement('search'), ['field_only' => true, 'nobox' => true]); ?> @ <?php echo $this->inputRow($this->searchForm->getElement('domain'), ['field_only' => true, 'nobox' => true]); ?>
                </p>
                <p id="useraddbutton">
                    <?php echo $this->SubmitRow($this->searchForm->getElement('submit'), ['nobox' => true, 'field_only' => true]) ?>
                </p>
            </form>
        </div>
        <div id="resultpanel">
            <?php echo $this->partial('ajax/user/search.phtml', [
                'elements' => $this->elements,
                'search' => $this->search,
                'elementscount' => $this->elementscount,
                'page' => $this->page,
                'lastpage' => $this->lastpage,
                'images_path' => $this->images_path,
                'domain' => $this->domain,
                'type' => $this->type,
                'editurl' => $this->editurl,
                't' => $this->t,
                'username' => $this->username,
                'elementdatafield' => $this->elementdatafield
            ]); ?>
        </div>
    </div>

    <div id="domaincontentpanel">
        <div id="userconfigpanel" class="domainconfigpanel">

            <?php if ($this->username != '') { ?>

                <h1 id="domaincontentpaneltitle"><?php echo $this->username; ?>

                    <?php if ($this->userobject->getId()) { ?>
                        <div id="removedomain" class="removedomain removedomaintitle"><a href="<?php echo $this->removeurl; ?>">
                                <?php if ($this->userobject->getDomainObject()->isAuthExhaustive()) {
                                    echo $this->t->_('Reset to default settings');
                                } else {
                                    echo $this->t->_('Remove from MailCleaner');
                                } ?>
                            </a></div>
                    <?php } ?>
                </h1>
                <form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>" id="<?php echo $this->form->getId() ?>">

                    <?php echo $this->partial('layouts/message.phtml', ['message' => $this->message, 't' => $this->t]); ?>
                    <h2><span>
                            <?php if ($this->userobject->getId()) { ?>
                                <?php echo $this->InputRow($this->form->getElement('userpanel'), ['field_only' => true, 'nobox' => true]); ?>
                            <?php } ?>
                        </span>
                    </h2>
                    <div id="domainformcontent">
                        <?php foreach (['panel', 'username', 'domain'] as $f) {
                            echo $this->InputRow($this->form->getElement($f), ['field_only' => true, 'nobox' => true]);
                        } ?>
                        <?php echo $this->partial('forms/manageuser/' . strtolower($this->panel) . 'Form.phtml', [
                            'form' => $this->form,
                            't' => $this->t,
                            'images_path' => $this->images_path,
                            'message' => $this->message,
                            'domain' => $this->domain,
                            'user' => $this->user,
                            'urls' => $this->urls,
                            'username' => $this->username
                        ]); ?>

                    </div>
                </form>
            <?php } else { ?>
                <?php $this->t->_('Please search or enter a user.'); ?>
            <?php } ?>
        </div>

    </div>

</div>
