<?php 
/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens
 * @copyright 2009, Olivier Diserens
 */
?>
<div id="loginpanel">

  <img id="mclogo" src="<?php echo $this->images_path; ?>/login_header.png" alt="" />
  <p id="badlogin">
<?php echo $this->error; ?>
  </p>
   
<?php
$this->form->setAction($this->url());
echo $this->form;

// Check if this is a registered version
require_once('system/SystemConfig.php');
$sysconf_ = SystemConfig :: getInstance();
require_once ('helpers/DataManager.php');
$file_conf = DataManager :: getFileConfig($sysconf_ :: $CONFIGFILE_);

$is_enterprise = $file_conf['REGISTERED'] == '1';
if ($is_enterprise)
        $mclink="www.mailcleaner.net";
else
        $mclink="www.mailcleaner.org";


?>

  <div id="loginfooter">
    <div class="copyright">&copy; <a href="<?php echo $mclink;?>"><?php echo $mclink; ?></a></div>
  </div>
</div>
