<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Mentor Reka, John Mertz
 * @copyright 2017, Mentor Reka; 2023, John Mertz
 */
?>
<div id="generalconfigpanel">
    <p class="contentheadicon"><img src="<?php echo $this->images_path ?>/config_icon.png" alt="" />&nbsp;</p>
    <p class="contentheadtitle"><?php echo $this->t->_($this->selectedSubMenu) ?> : <?php echo $this->t->_($this->selectedConfigMenuLabel) ?></p>


    <ul id="generalconfigmenu">
        <?php foreach ($this->config_menu as $menu) { ?>
            <li id="confmenu_<?php echo $menu->id ?>" <?php if ($menu->class) { ?>class="<?php echo $menu->class ?>" <?php } ?> onclick="javascript:goTo('<?php echo $menu->getHref() ?>');"><a href="<?php echo $menu->getHref() ?>"><?php echo $menu->label; ?></a></li>
        <?php } ?>
    </ul>

    <div id="generalconfigcontent">
        <div id="interfaceconfigpanel" class="configpanel">

            <div id="proxiesformcontent">
                <?php echo $this->partial('forms/autoconfigurationForm.phtml', ['form' => $this->form, 't' => $this->t, 'message' => $this->message, 'images_path' => $this->images_path]); ?>
            </div>
        </div>
    </div>
</div>
