<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<?php foreach (['panel', 'username', 'domain'] as $f) {
    echo $this->InputRow($this->form->getElement($f), ['field_only' => true, 'nobox' => true]);
} ?>
<?php echo $this->partial(
    'forms/manageuser/' . strtolower($this->panel) . 'Form.phtml',
    [
        'form' => $this->form,
        't' => $this->t,
        'images_path' => $this->images_path,
        'message' => $this->message,
        'domain' => $this->domain,
        'user' => $this->user,
        'urls' => $this->urls,
        'username' => $this->username
    ]
); ?>
