<?php

/**
 * @license http://www.mailcleaner.net/open/licence_en.html Mailcleaner Public License
 * @package mailcleaner
 * @author Olivier Diserens, John Mertz
 * @copyright 2009, Olivier Diserens; 2023, John Mertz
 */
?>
<ul id="generalconfigmenu">
    <?php foreach ($this->config_menu as $menu) { ?>
        <li id="confmenu_<?php echo $menu->id ?>" <?php if ($menu->class) { ?>class="<?php echo $menu->class ?>" <?php } ?> onclick="javascript:goTo('<?php echo $menu->getHref() ?>');"><a href="<?php echo $menu->getHref() ?>"><?php echo $menu->label; ?></a></li>
    <?php } ?>
</ul>
